/**
 * GENERATED by `bun run build:particle-image` — do not edit.
 *
 * The source of truth is `apps/point-cloud/src/shaders/`. This file exists so
 * the component works in a project with no GLSL loader configured; re-run the
 * script after changing a shader.
 */

export const particleVertexShader = `// Point transform, motion and size.
//
// ShaderMaterial prepends the built-ins used here: the \`position\` attribute
// and the \`modelViewMatrix\` / \`projectionMatrix\` uniforms.
//
// P3.1 — \`position\` is now all zeros and is never read. A particle is no
// longer handed its place in the world; it is handed an address (aParticleUv,
// the centre of its texel) and works the rest out on the GPU.
//
// P3.2 — the address starts paying off: the colour comes from this particle's
// own texel.
//
// P3.3/P3.4 — and so does the position. Nothing about where a particle sits
// is computed here any more; it is read out of two textures and mapped back
// onto the bundle's bounds. The placeholder grid is gone.
//
// P4 — on top of that fixed home position sits the motion: curl noise in clip
// space (4.2, 4.3) plus a slow breathing in depth (4.4). None of it is
// simulated. Every frame recomputes the whole offset from time alone, so
// there is no state to keep, no error to accumulate, and no cost per particle
// beyond the arithmetic itself.

// ---- inlined pc_noise ----
// Value noise, fBM and 2D curl noise (P4.1, P4.2).
//
// Registered as a three.js ShaderChunk in scene/shader-chunks.ts, so
// points.vert.glsl pulls it in with \`#include <pc_noise>\` — the same mechanism
// three.js uses for its own chunks, and the only way a .glsl file loaded
// through raw-loader can be shared between shaders.

// A pseudo-random number for one lattice corner. The multipliers are large so
// that inputs sitting right next to each other (cell 4 and cell 5) land on
// completely unrelated values — which is the entire job of a noise hash.
float pcHash(vec2 p) {
  p = fract(p * vec2(123.34, 456.21));
  p += dot(p, p + 45.32);
  return fract(p.x * p.y);
}

// Value noise: a random number at every integer lattice point, smoothly
// interpolated in between. Cheaper than gradient (Perlin) noise, and once
// several octaves are stacked the difference stops being visible.
float pcValueNoise(vec2 p) {
  vec2 cell = floor(p);
  vec2 f = fract(p);

  // Smoothstep the blend weights. Interpolating linearly would leave visible
  // creases along every lattice line, because the slope changes abruptly there
  // even though the value does not.
  vec2 w = f * f * (3.0 - 2.0 * f);

  float a = pcHash(cell);
  float b = pcHash(cell + vec2(1.0, 0.0));
  float c = pcHash(cell + vec2(0.0, 1.0));
  float d = pcHash(cell + vec2(1.0, 1.0));

  return mix(mix(a, b, w.x), mix(c, d, w.x), w.y);
}

// Fractal Brownian motion: the same noise summed at doubling frequencies and
// halving amplitudes. One octave is soft blobs and reads as artificial; four
// carries both large shapes and fine detail, which is what natural texture
// looks like — coastlines, clouds and mountains all behave this way.
//
// Each octave is also rotated. Skip that and every octave shares the same
// lattice directions, so their sum shows a faint grid aligned to the axes: the
// noise looks subtly square. Half a radian per octave is enough to break it.
#define PC_FBM_OCTAVES 4

float pcFbm(vec2 p) {
  // cos(0.5), sin(0.5) — mat2 takes its arguments column by column.
  const mat2 rotate = mat2(0.8775826, 0.4794255, -0.4794255, 0.8775826);

  float sum = 0.0;
  float amplitude = 0.5;

  for (int i = 0; i < PC_FBM_OCTAVES; i++) {
    sum += amplitude * pcValueNoise(p);
    p = rotate * p * 2.0;
    amplitude *= 0.5;
  }

  return sum;
}

// The 2D curl of the fBM field, by central difference.
//
// Take the gradient of a scalar field and rotate it by 90°. The result is
// divergence-free: as much flows out of any small region as flows into it.
// That property is the whole reason to bother. Follow a plain gradient and
// every particle slides downhill into the same few basins and stays there;
// follow its curl and particles circulate forever without ever piling up.
//
// Four fBM evaluations per particle is the cost, and it is the most expensive
// thing in the frame. P9.2 drops an octave for mobile.
vec2 pcCurl(vec2 p) {
  const float e = 0.08;

  float dx = pcFbm(p + vec2(e, 0.0)) - pcFbm(p - vec2(e, 0.0));
  float dy = pcFbm(p + vec2(0.0, e)) - pcFbm(p - vec2(0.0, e));

  // (∂ψ/∂y, −∂ψ/∂x)
  return vec2(dy, -dx) / (2.0 * e);
}

// ---- end pc_noise ----
// ---- inlined pc_lut ----
// 3D colour lookup, from a cube flattened into a 2D image (P5.2).
//
// Registered as a ShaderChunk in scene/shader-chunks.ts: \`#include <pc_lut>\`.
//
// WebGL 1 has no 3D textures, so the 64x64x64 cube is stored as 64 slices of
// 64x64 laid out in an 8x8 grid — one 512x512 PNG. Within a slice, red runs
// left to right and green top to bottom; the slice index is blue.
//
//   ┌────┬────┬────┬────┬────┬────┬────┬────┐
//   │ b0 │ b1 │ b2 │ b3 │ b4 │ b5 │ b6 │ b7 │   each cell: 64x64
//   ├────┼────┼────┼────┼────┼────┼────┼────┤   red  →
//   │ b8 │ b9 │ …  │    │    │    │    │    │   green ↓
//   └────┴────┴────┴────┴────┴────┴────┴────┘

const float PC_LUT_SIZE = 64.0;
const float PC_LUT_TILES = 8.0;
const float PC_LUT_IMAGE = 512.0;

vec3 pcLutLookup(sampler2D lut, vec3 color) {
  vec3 c = clamp(color, 0.0, 1.0);

  // Blue picks the slice. It almost never lands exactly on one, so read the
  // two neighbouring slices and blend — this is the third dimension of the
  // interpolation, which the hardware cannot do for us across tiles.
  float blue = c.b * (PC_LUT_SIZE - 1.0);
  float slice = floor(blue);
  float next = min(slice + 1.0, PC_LUT_SIZE - 1.0);
  float blend = blue - slice;

  // Where inside a tile. The +0.5 lands on a texel centre, and scaling by
  // (size - 1) before that keeps the lookup inside the tile's own 64 texels:
  // bilinear filtering must never reach across a tile border, because the
  // neighbour is a completely different blue.
  vec2 inside = (c.rg * (PC_LUT_SIZE - 1.0) + 0.5) / PC_LUT_IMAGE;

  vec2 tile = vec2(mod(slice, PC_LUT_TILES), floor(slice / PC_LUT_TILES)) / PC_LUT_TILES;
  vec2 tileNext = vec2(mod(next, PC_LUT_TILES), floor(next / PC_LUT_TILES)) / PC_LUT_TILES;

  return mix(
    texture2D(lut, tile + inside).rgb,
    texture2D(lut, tileNext + inside).rgb,
    blend
  );
}

// Grades are authored on the values you see on screen, not on linear light, so
// the round trip has to happen around the lookup. Skipping it does not fail
// loudly — it just makes every grade act far more strongly in the shadows than
// whoever built it intended.
vec3 pcGrade(sampler2D lut, vec3 linearColor, float intensity) {
  vec3 display = pow(clamp(linearColor, 0.0, 1.0), vec3(1.0 / 2.2));
  vec3 graded = pow(pcLutLookup(lut, display), vec3(2.2));

  return mix(linearColor, graded, intensity);
}

// ---- end pc_lut ----

attribute vec2 aParticleUv;  // centre of this particle's texel, in (0, 1)

uniform sampler2D uColorMap;      // one texel of colour per particle
uniform sampler2D uPositionHigh;  // high byte of each 16-bit coordinate
uniform sampler2D uPositionLow;   // low byte
uniform vec3 uBoundsMin;          // world extent the 0..1 values map onto
uniform vec3 uBoundsMax;
uniform float uTextureSize;  // side of the square data texture, in texels
uniform float uSize;         // point size in world units
uniform float uScale;        // half the drawing-buffer height, in device pixels
uniform float uMaxPointSize; // largest gl_PointSize this GPU supports
uniform float uTime;         // seconds of animation, advanced on the CPU
uniform float uNoiseAmplitude; // curl offset, in normalised device units
uniform float uNoiseFrequency; // how many noise cells span the cloud
uniform float uNoiseScatter;   // how far apart neighbours sample the field
uniform float uBreathe;        // depth breathing, in world units
uniform float uViewportAspect; // width / height, to keep the wobble round
uniform float uDebugNoise;     // 1 = show the fBM field instead of the photo
uniform float uFocalDepth;     // which depth slice is sharp, 0..1 across bounds
uniform float uFocalRange;     // how much depth stays sharp around it
uniform float uEdgeBokeh;      // how strongly the left and right edges soften
uniform sampler2D uLut;        // colour grade, a 64^3 cube flattened to 512x512
uniform float uLutIntensity;   // 0 = ungraded, 1 = the grade in full
uniform float uProgress;       // intro progress, 0 -> 1 (P5.5)
uniform float uDensityBoost;   // how much the loneliest points grow (P5.1)

varying float vCoverage; // how much of the 1px minimum the point really fills
varying vec3 vColor;     // this particle's colour, fetched from uColorMap
varying float vDefocus;  // 0 = sharp, 1 = fully outside the focal slice (P5.3)
varying float vEdge;     // 0 in the middle of frame, up to 1 at the sides (P5.4)
varying float vReveal;   // 0 before this particle arrives, 1 once it has (P5.5)

// Deterministic pseudo-randomness from a 2D coordinate (Dave Hoskins' hash32).
// This replaces the aScale / aRandomness attributes of P1.4-P1.5: the same
// texel always produces the same numbers, on every machine, with no CPU buffer
// to upload or keep in sync.
//
// Feed it texel coordinates (0 .. size), never uv (0 .. 1). The first fract()
// is what decorrelates neighbours, and fract() of a number below 1 returns the
// number unchanged — with uv the hash would degrade into a smooth ramp.
vec3 hash32(vec2 p) {
  vec3 p3 = fract(p.xyx * vec3(0.1031, 0.1030, 0.0973));
  p3 += dot(p3, p3.yxz + 33.33);
  return fract((p3.xxy + p3.yzz) * p3.zyx);
}

void main() {
  vec2 texel = aParticleUv * uTextureSize;

  // P3.3 — one coordinate, two bytes. A PNG channel holds 256 levels, which
  // over this field is a step the size of a whole grid cell; two channels give
  // 65,536 levels and a step 250x finer. The divisor is 65535, not the 65536
  // the original UntilLabs shader uses: two bytes span 0..65535 inclusive, so
  // 65535 is the value that has to land on 1.0. See src/bundle/position-codec.ts.
  vec3 high = texture2D(uPositionHigh, aParticleUv).rgb * 255.0;
  vec3 low = texture2D(uPositionLow, aParticleUv).rgb * 255.0;
  vec3 normalised = (high * 256.0 + low) / 65535.0;

  // P3.4 — the PNGs only ever hold 0..1. metadata.json says what range that
  // stands for, which is how the format stays both small and precise: every
  // one of the 65,536 levels is spent on ground the cloud actually covers.
  vec3 home = mix(uBoundsMin, uBoundsMax, normalised);

  // Three vertex texture fetches, 65,536 particles, all in parallel. These are
  // the lines the whole P3 phase exists to make possible.
  vec4 colorSample = texture2D(uColorMap, aParticleUv);
  vColor = colorSample.rgb;

  // P5.1/P6.6 — the alpha channel of the colour map carries how crowded this
  // particle is: 1 where points are packed tight, 0 out in the sparse
  // background. It rides in alpha because alpha is the one channel sRGB does
  // not put through a transfer curve, so the number arrives as the number —
  // and because a bundle whose colour map has no alpha reads back 1.0, which
  // means "densest", which leaves the size alone. Every pre-6.6 bundle keeps
  // rendering exactly as it did.
  float crowding = colorSample.a;

  // P5.2 — the colour grade. It runs here, once per particle, rather than in
  // the fragment shader: the colour is constant across a point sprite, so
  // grading per pixel would repeat the same two texture fetches for every one
  // of the dozens of pixels a point covers.
  //
  // The article describing the original puts the LUT in the post-processing
  // pass. Reading their shipped code shows it applied in the particle shader
  // instead, with the post shader declaring a LUT uniform it never uses.
  vColor = pcGrade(uLut, vColor, uLutIntensity);

  vec3 randomness = hash32(texel);

  // Per-particle size variation reads as depth and texture (P1.4), but it also
  // means the field below is sampled by dots of differing weight. The debug
  // view flattens them so what you see is the noise, not the sampling.
  float scale = mix(mix(0.5, 1.0, hash32(texel + 91.7).y), 0.8, uDebugNoise);

  // P4.2 — where this particle samples the flow field. The scatter term is
  // what decides whether neighbours move together or apart: at 0 the cloud
  // behaves like a sheet in a breeze, and as it grows each particle wanders
  // its own way. It comes from the texel hash rather than aIndex directly,
  // because hashing a five-digit integer runs out of float precision (P3.1).
  vec2 flowSeed = aParticleUv * uNoiseFrequency
                + randomness.xy * uNoiseScatter
                + uTime * 0.12;

  // P4.1 — the debug view. Painting the fBM field onto the same particles is
  // the cheapest way to see what the motion is actually being driven by.
  //
  // Two corrections make it legible. fBM is an average of averages, so its
  // values crowd around 0.5 and the raw field is nearly flat grey — hence the
  // contrast stretch. And vColor is linear light that the fragment shader
  // encodes to sRGB at the end, which lifts mid grey to near white; raising it
  // to 2.2 first cancels that out, so what reaches the screen is the field.
  float field = clamp((pcFbm(flowSeed) - 0.2) / 0.55, 0.0, 1.0);
  vColor = mix(vColor, vec3(pow(field, 2.2)), uDebugNoise);

  // P4.4 — breathing. A slow sine in depth, with a per-particle phase so the
  // surface undulates instead of sliding back and forth as one slab.
  home.z += sin(uTime * 0.25 + randomness.z * 6.2831) * uBreathe;

  // Object space -> camera (view) space. The camera looks down -z,
  // so -mvPosition.z is the distance in front of it.
  vec4 mvPosition = modelViewMatrix * vec4(home, 1.0);

  // P4.4 — and a faster wobble that only wakes up close to the camera, where
  // there are enough pixels for it to register. Far away it would be motion
  // nobody can see, paid for at full price.
  float nearness = smoothstep(3.2, 1.2, -mvPosition.z);
  mvPosition.z += sin(uTime * 0.5 + randomness.x * 6.2831) * nearness * uBreathe * 0.6;

  // View space -> clip space; the GPU then divides by w for perspective.
  gl_Position = projectionMatrix * mvPosition;

  // P4.3 — the curl offset is added *after* the projection, in clip space.
  // Multiplying by w cancels the perspective divide that follows, so the
  // displacement is a fixed distance on screen no matter how far away the
  // particle is. Offsetting in world space instead would make near particles
  // swing wildly while distant ones barely twitched.
  vec2 flow = pcCurl(flowSeed);
  flow.x /= uViewportAspect; // NDC is square; the viewport usually is not
  gl_Position.xy += flow * uNoiseAmplitude * gl_Position.w;

  // P5.5 — the intro. One uniform counts from 0 to 1, and every particle reads
  // its own arrival out of it. No timeline, no per-particle state, no CPU work
  // that scales with the count: 65,536 independent animations from one float.
  //
  // The delay mixes two kinds of randomness on purpose. Pure per-particle noise
  // makes the cloud fade up as an even haze; pure fBM makes whole regions
  // arrive together in slabs. Four parts grain to six parts clump gives
  // patches that materialise at their own pace with ragged edges.
  float grain = hash32(texel + 41.3).z;
  float clump = pcFbm(aParticleUv * 2.0);
  float delay = mix(grain, clump, 0.4) * 0.62;

  // And a focus ring opening out of the centre, its edge chewed up by noise so
  // it never reads as a circle — a lens hunting for focus rather than a wipe.
  vec2 fromCentre = aParticleUv - 0.5;
  float radius = length(fromCentre);
  float angle = atan(fromCentre.y, fromCentre.x);
  float ragged = pcFbm(vec2(angle * 1.7, radius * 5.0)) * 0.13 + sin(angle * 6.0) * 0.025;
  float ring = smoothstep(radius + ragged - 0.09, radius + ragged + 0.09, uProgress * 0.92);

  vReveal = min(smoothstep(delay, delay + 0.34, uProgress), ring);

  // P5.4 — edge bokeh. Particles near the left and right edges are blown up,
  // faded, and pushed a little further out, which is roughly what a fast lens
  // does to anything away from its centre. It frames the subject without
  // drawing a frame.
  //
  // Measured in NDC, so it follows the screen rather than the cloud: dividing
  // clip x by w is the perspective divide the GPU is about to do anyway.
  vEdge = smoothstep(0.55, 1.0, abs(gl_Position.x / gl_Position.w)) * uEdgeBokeh;
  gl_Position.x *= 1.0 + vEdge * 0.3;

  // Points have no geometry for the projection to shrink, so perspective is
  // applied by hand: a world-sized point covers fewer pixels further away.
  // uScale is in device pixels and carries the 1/tan(fov/2) of the lens, so
  // the apparent size is right at any devicePixelRatio, viewport or focal
  // length — zooming in with the FOV slider grows the points with the scene.
  float pixels = uSize * scale * (uScale / -mvPosition.z);

  // P5.1 — grow the lonely points. The sampler puts far fewer points on flat
  // background than on the subject, which is the whole idea, and at one size
  // that background shows through as holes.
  //
  // The exponent is not arbitrary. Crowding is a *logarithmic* measure of
  // spacing (P6.6): every 0.5 it drops means the neighbours are three times
  // further away. Undoing a logarithm takes an exponential, so pow() with the
  // square of that three is what makes point size track spacing exactly at a
  // boost of 1. Written this way it is also 1.0 when crowding is 1, so a
  // bundle whose colour map has no alpha is left alone.
  pixels *= pow(9.0, (1.0 - crowding) * uDensityBoost);

  // P5.3 — fake depth of field. Real DOF spreads an out-of-focus point into a
  // disc, which post-processing does by blurring the whole frame at great
  // expense. A point cloud can cheat: shrink the point and fade it instead.
  // The gaps that opens between neighbours read as softness, and it costs two
  // multiplies inside a shader that was already running.
  //
  // The slice is measured along the cloud's own depth (\`normalised.z\`, 0..1
  // across the bundle's bounds) rather than distance from the camera. For a
  // photograph lifted into shallow relief that is the meaningful axis — and
  // it means the focus does not drift while you orbit.
  vDefocus = smoothstep(0.0, max(uFocalRange, 0.001), abs(normalised.z - uFocalDepth));
  pixels *= 1.0 - vDefocus * vDefocus * 0.5;
  pixels *= 1.0 + vEdge * 1.4;
  // Arriving particles grow into place rather than blinking on.
  pixels *= 0.4 + 0.6 * vReveal;

  // The GPU cannot draw less than one pixel: a 0.3px point would be drawn as
  // a full pixel and look too bright. Draw 1px but let the fragment shader
  // dim it by the area the point should have covered (0.3² = 9%).
  vCoverage = min(pixels * pixels, 1.0);

  // Past the hardware limit the GPU clamps silently; clamping here keeps the
  // behavior explicit and identical across devices.
  gl_PointSize = clamp(pixels, 1.0, uMaxPointSize);
}
`;

export const particleFragmentShader = `// Runs once per pixel covered by each point.

uniform float uSoftness;  // 0 = hard disc, 1 = fades all the way from the center

varying float vCoverage; // < 1 for points smaller than a pixel (P1.4)
varying vec3 vColor;     // linear-space color read from the data texture (P3.2)
varying float vDefocus;  // 0 = sharp, 1 = fully outside the focal slice (P5.3)
varying float vEdge;     // 0 mid-frame, up to 1 at the sides (P5.4)
varying float vReveal;   // 0 before this particle arrives, 1 once it has (P5.5)

void main() {
  // P1.3 — a point is rasterised as a square sprite. gl_PointCoord is this
  // pixel's position inside that square, (0,0) top-left to (1,1) bottom-right.
  // Distance from the center: 0 in the middle, 0.5 at the edge midpoints,
  // ~0.707 in the corners.
  float d = length(gl_PointCoord - 0.5);

  // Throw away the corners: discard skips this pixel entirely (no color, no
  // depth write), which is what turns the square into a disc.
  if (d > 0.5) discard;

  // Fade the rim instead of cutting it: full alpha inside, down to 0 at the
  // edge. The fade band starts at 0.5 * (1 - softness).
  float alpha = 1.0 - smoothstep(0.5 * (1.0 - uSoftness), 0.5, d);

  // P5.3 / P5.4 — the other half of the cheat. Shrinking a point opens gaps;
  // fading it is what turns those gaps into softness rather than sparseness.
  // The floor matters: drop it much below this and a defocused sky stops
  // being soft and simply disappears, which is a hole in the picture rather
  // than depth of field.
  alpha *= mix(1.0, 0.14, vDefocus * vDefocus);
  alpha *= 1.0 - vEdge * 0.55;
  alpha *= vReveal;

  gl_FragColor = vec4(vColor, alpha * vCoverage);

  // Convert linear -> the renderer's output color space (sRGB). Without this
  // chunk the same color looks darker than it does with PointsMaterial.
  #include <colorspace_fragment>
}
`;
