/**
 * Embeds the app's shaders into the drop-in component (P8.6).
 *
 *   bun run build:particle-image
 *
 * `<ParticleImage>` has to work in **somebody else's project**, which means it
 * cannot assume raw-loader, or a bundler that imports `.glsl`, or three's
 * `ShaderChunk` registry having been populated by a module side effect. The
 * only thing every setup agrees on is a string.
 *
 * So the GLSL is copied into `shaders.gen.ts` as template literals, with the
 * `#include <pc_noise>` directives resolved in place — the same substitution
 * `ShaderChunk` does at runtime, done here instead.
 *
 * Generated and committed, on purpose: someone copying the package out of this
 * repo should not have to run a build step to get a component that works. The
 * cost is that the file goes stale if the shaders change and this is not
 * re-run, which is why it says so at the top of itself.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const here = fileURLToPath(new URL(".", import.meta.url));
const shaders = `${here}../src/shaders`;
const out = `${here}../../../packages/particle-image/src/shaders.gen.ts`;

const chunks: Record<string, string> = {
  pc_noise: readFileSync(`${shaders}/noise.glsl`, "utf8"),
  pc_lut: readFileSync(`${shaders}/lut.glsl`, "utf8"),
};

/** Resolve `#include <name>` against the chunks, the way three.js would. */
function resolveIncludes(source: string): string {
  return source.replace(/^#include <(\w+)>$/gm, (line, name: string) => {
    const chunk = chunks[name];
    if (chunk === undefined) {
      // three's own chunks (`<colorspace_fragment>`) must survive untouched:
      // the consumer's ShaderMaterial still resolves those at compile time.
      return line;
    }
    return `// ---- inlined ${name} ----\n${chunk}\n// ---- end ${name} ----`;
  });
}

/** Backticks and `${` would end the template literal early. */
function asTemplate(source: string): string {
  return source.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const vertex = resolveIncludes(readFileSync(`${shaders}/points.vert.glsl`, "utf8"));
const fragment = resolveIncludes(readFileSync(`${shaders}/points.frag.glsl`, "utf8"));

const file = `/**
 * GENERATED by \`bun run build:particle-image\` — do not edit.
 *
 * The source of truth is \`apps/point-cloud/src/shaders/\`. This file exists so
 * the component works in a project with no GLSL loader configured; re-run the
 * script after changing a shader.
 */

export const particleVertexShader = \`${asTemplate(vertex)}\`;

export const particleFragmentShader = \`${asTemplate(fragment)}\`;
`;

writeFileSync(out, file);
console.log(`wrote ${out}`);
console.log(`vertex ${vertex.length} chars, fragment ${fragment.length} chars`);
